### PR TITLE
Support fold-case and no-fold-case directive

### PR DESCRIPTION
**Pull request by higepon**

### CODE REVIEW

**Comment by lassik** [comment]
Nb. I've never seen any actual R7RS code using `#!fold-case`. It seems the Scheme community has reached de facto agreement to use case sensitive identifiers.

**Comment by higepon** [comment]
thank you. That's good to know. I would not worry too much about this then.

**Comment by lassik** [comment]
For completeness, here's a [survey](https://docs.scheme.org/surveys/case-insensitivity/) by John Cowan and Shiro Kawai. It's somewhat old; the trend is toward case sensitive by default.)

**Comment by higepon** [comment]
Thank you. I can see the trend too.

**Pull request merged**
