### PR TITLE
Support more (scheme ...) libraries

### PR DESCRIPTION
**Pull request by higepon**
Now mosh can execute the following script.
Note: importing ```(scheme r5rs)``` causes ```message: "two imports with different bindings"``` for some procedures such as ```write``` which makes sense. I'll have to look into r7rs small later.

```
(import ; (scheme r5rs)
        (scheme case-lambda)
        (scheme process-context)
        (scheme write)
        (scheme eval)
        (scheme file)
        (scheme time)
        (scheme complex)
        (scheme inexact)
        (scheme lazy)
        (scheme char)
        (scheme base)
        (scheme read)
)
```

### CODE REVIEW

**Review by okuoku — APPROVED** [review]
Please note that you still have to bind `_` somewhere, as same as `...`. I think it's still okay for now; IIRC, psyntax do not have binding for it.

(AFAIK, Chicken do not bind it though. https://github.com/okuoku/yuni/blob/master/doc/sibr/SIBR0001-AUX-KEYWORDS.md )

**Comment by higepon** [comment]
> Please note that you still have to bind `_` somewhere, as same as `...`. I think it's still okay for now; IIRC, psyntax do not have binding for it.
> 
> (AFAIK, Chicken do not bind it though. https://github.com/okuoku/yuni/blob/master/doc/sibr/SIBR0001-AUX-KEYWORDS.md )

Noted. Thank you for your review!

**Comment by lassik** [comment]
> Note: importing `(scheme r5rs)` causes `message: "two imports with different bindings"` for some procedures such as `write` which makes sense.

That's ok. `(scheme r5rs)` is a compatibility library that is rarely imported.

**Comment by lassik** [comment]
I.e. programs are not supposed to import `(scheme base)` and `(scheme r5rs)` at the same time.

**Comment by higepon** [comment]
@lassik 
Thanks for confirming.
I saw it in https://github.com/ashinn/chibi-scheme/blob/master/tests/r7rs-tests.scm and was wondering if there's any rules to prioritize duplicated identifiers :)

**Comment by lassik** [comment]
Section 5.2. "Import declarations":

> In a program or library declaration, it is an error to import the same identifier more than once with different bindings,
or to redefine or mutate an imported binding with a definition or with set!, or to refer to an identifier before it is imported. However, a REPL should permit these actions.

**Comment by lassik** [comment]
In R7RS, "it is an error" means approximately the same as "undefined behavior".

**Pull request merged**
