### PR TITLE
Support (srfi 1) in R7RS

### PR DESCRIPTION
**Pull request by higepon**

### CODE REVIEW

**Comment by okuoku** [comment]
Caveat of this approach is you'll have to copy&paste `export` clause from original library.

Uh, but yeah it can be generated automatically within `./gen-git-build.sh`...

**Comment by higepon** [comment]
Ah. Actually I think it's a good idea to do it using script. Should be very trivial and clean.

**Review by okuoku — APPROVED** [review]
Perhaps we'd also want to test we can import both R6RS/R7RS at the same time.

```
(import (srfi 1) (srfi :1 lists))
```

**Comment by higepon** [comment]
> Perhaps we'd also want to test we can import both R6RS/R7RS at the same time.
> 
> ```
> (import (srfi 1) (srfi :1 lists))
> ```

Thanks for your approval. What do you mean? it will cause duplicated identifier right?

**Comment by okuoku** [comment]
> What do you mean?

1. Real world apps won't be pure R6RS nor R7RS; it will import both R6RS library and R7RS library on a single `import` clause. Thus it's worth to ensure we can import both format libraries at once.
2. We should ensure both R6RS version of SRFI-XXX and R7RS ones export exact same identifier. Simple way to ensure it would be check if we can `(import (srfi 1) (srfi :1))` flawlessly.

**Comment by higepon** [comment]
Good point. I think it's working as expected as of now.

**Pull request merged**
